/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:95855886-5e07-4b53-9e31-69cb4e3879f9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_C7gsK5Iug",
    "aws_user_pools_web_client_id": "q300o3fdg7heqnu4mbprn2p0a",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://xnu5ji6q7nhvtjccybe6mrdxii.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
